version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "venus/beeple"
    ports:
      - "8080:8080"
  venus-mysql:
    image: mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=venus
      - MYSQL_USER=venus
      - MYSQL_PASSWORD=venusßß
    ports:
      - 3306:3306
